### PR TITLE
Ensuring that at least one file upload is provided for draft Works

### LINKED ISSUE #1772: Validation for Awaiting Approval (end of wizard) Need to check for Readme and Other files explicitly
The user should not be able to mark a submission as complete unless a README file exists AND some other file.

Completion Criteria:
- [x] When a user Click Grant License and Complete the controller should validate the uploaded files
  - [x] There Must be one and only one README.
  - [x] There Must be one or more other files if they are uploading locally
- [x] If the right files do not exists the user will see an error on the page and the work will not update state
  - [x] Readme error: "You Must include a README. [Please upload  one][link to readme step]"
  - [x] File error "You Must include at least one file. [Please upload  one][link to upload step]"

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #1772

### CODE REVIEW

**Review by bess — APPROVED** [review]

**Comment by carolyncole** [comment]
@jrgriffiniii I think the fact that the code allows readmes that are not named readme is messing up the logic.  I just deployed this branch, upoloaded my usual readme `_Readme.txt` and was able to complete this one without uploading any additional files https://pdc-describe-staging.princeton.edu/describe/works/611

**Comment by jrgriffiniii** [comment]
The README can now be any name which has `readme` in it. This is a bug.

**Comment by carolyncole** [comment]
@hectorcorrea has suggested that the count of files should be greater than 1 and the readme exists should solve this.

**Comment by carolyncole** [comment]
@jrgriffiniii I went ahead and worked on this PR to make it green.  I reverted some of your changes to the Readme and I did not understand them and they were making the tests fail.  Lets discuss!

**Review by bess — APPROVED** [review]

**Pull request merged**
