### PR TITLE
Minimalist UI for prov and messages

### PR DESCRIPTION
**Pull request by mccalluc**
@hhkitsune should review this and see if the simplified UI is closer to what she wants, and if it is better, what additional tweaks are needed, if any.

Not that there are other PRs in the wings which will also make improvements here:
- #814
- #821 
- #819

before and after:
Screen Shot 2023-01-06 at 1 32 05 PM

### CODE REVIEW

**Comment by hhkitsune** [comment]
@mccalluc I love the appearance of the provenance! It is perfect. Thank you so much. : )

I'm not sure why the messages (currently called "comments") look this way though. It should only be the provenance that has this appearance and message feature should be more consistent with how messages typically look. Regarding messages, I just wrote a ticket for changes to the messaging feature that was discussed in our last feature refinement meeting. Bess just took a look at it and said the ticket was actionable. You might also want to have a look: #823. Please feel welcome to comment or ask questions.

**Comment by mccalluc** [comment]
> I'm not sure why the messages (currently called "comments") look this way though.

Both sections were using the same style before, so the simplest change was to make a single change, rather than adding special cases. But that is doable. I'll update this PR.

**Comment by hhkitsune** [comment]
@mccalluc Thanks, much appreciated!

**Comment by mccalluc** [comment]
Updated screen shot, with a distinct style for messages, and other recent features merged in. Tests are looking for particular elements, but the structure of the page has changed. Will fix.

#823 will be handled separately: We want to keep this to a small set of changes.

Screen Shot 2023-01-06 at 4 36 30 PM

**Review by bess — APPROVED** [review]

**Pull request merged**
