### PR TITLE
Added a class to the required star to make it more visible

### PR DESCRIPTION
**Pull request by carolyncole**
We made the start 1.5 em since that seemed to match with the change in the ticket.

Additionally fixes a bug in the work_spec where the new ROR was not included in the bi directional second drag, so the test was dragging the row forward and then backward.  Why making the star larger surfaced this issue, I am unsure...

refs #1293

### CODE REVIEW

**Comment by hectorcorrea** [comment]
Go home CircleCI --  you are drunk. Re-running the test to see if that fixes it.

**Review by hectorcorrea — DISMISSED** [review]

**Comment by hectorcorrea** [comment]
The test failure seems to be a real one in this case (?)
```
expected: "Sally Smith National Science Foundation https://ror.org/021nxhr62  Quyen Jacobi"
got: "Quyen Jacobi    Sally Smith National Science Foundation https://ror.org/021nxhr62"

```

**Comment by carolyncole** [comment]
> The test failure seems to be a real one in this case (?)
> 
> ```
> expected: "Sally Smith National Science Foundation https://ror.org/021nxhr62  Quyen Jacobi"
> got: "Quyen Jacobi    Sally Smith National Science Foundation https://ror.org/021nxhr62"
> ```

It does not fail locally for me, but does repetitively in CI.  🤞 rebasing on flapping test  branch will solve it.

**Comment by carolyncole** [comment]
OMG!  Ok, so after a bit of digging it is the change in the `app/assets/stylesheets/application.scss` that is breaking the test.  I removed that change and the tests went green...  I'll do some more digging

**Comment by carolyncole** [comment]
Ok, so after digging into this further making the stars bugger in the table header are messing with the drag and drop in some way.

**Review by hectorcorrea — APPROVED** [review]

**Pull request merged**
